import type { BlueprintParam, BlueprintPropertyMeta, PortEntity } from "../types";

export const MOCK_BLUEPRINT: BlueprintParam = {
  identifier: "service",
  title: "Service",
};

export const MOCK_BLUEPRINT_PROPERTIES: BlueprintPropertyMeta[] = [
  { identifier: "tier", title: "Tier", type: "string", kind: "default" },
  { identifier: "owner", title: "Owner", type: "string", kind: "default" },
  { identifier: "tags", title: "Tags", type: "array", kind: "array" },
  { identifier: "language", title: "Language", type: "string", kind: "default" },
  { identifier: "on_call", title: "On-call", type: "string", kind: "default" },
  {
    identifier: "team_name",
    title: "Team name",
    kind: "default",
  },
  {
    identifier: "status",
    title: "Status",
    type: "string",
    kind: "default",
  },
  {
    identifier: "issue_type",
    title: "Type",
    type: "string",
    kind: "default",
  },
  { identifier: "enabled", title: "Enabled", type: "boolean", kind: "boolean" },
  {
    identifier: "slo_defined",
    title: "SLO defined",
    type: "boolean",
    kind: "boolean",
  },
];

export const MOCK_ENTITIES_PAGE: PortEntity[] = [
  {
    identifier: "checkout",
    title: "Checkout",
    properties: {
      tier: "Tier 1",
      owner: "Payments",
      tags: ["payments", "critical", "pci"],
      language: "TypeScript",
      on_call: "payments-oncall",
      team_name: "Payments Squad",
      status: "In Progress",
      issue_type: "Story",
      enabled: true,
      slo_defined: true,
    },
  },
  {
    identifier: "auth",
    title: "Auth Service",
    properties: {
      tier: "Tier 1",
      owner: "Platform",
      tags: ["security", "identity"],
      language: "Go",
      on_call: "platform-oncall",
      status: "Done",
      issue_type: "Task",
      enabled: true,
      slo_defined: true,
    },
  },
  {
    identifier: "notifications",
    title: "Notifications",
    properties: {
      tier: "Tier 2",
      owner: "Growth",
      tags: ["messaging"],
      language: "Python",
      on_call: "growth-oncall",
      status: "To Do",
      issue_type: "Bug",
      enabled: true,
      slo_defined: false,
    },
  },
  {
    identifier: "search",
    title: "Search",
    properties: {
      tier: "Tier 2",
      owner: "Discovery",
      tags: ["search", "ml", "indexing", "ranking"],
      language: "Java",
      on_call: "discovery-oncall",
      status: "In Progress",
      issue_type: "Story",
      enabled: true,
      slo_defined: true,
    },
  },
  {
    identifier: "billing",
    title: "Billing",
    properties: {
      tier: "Tier 1",
      owner: "Payments",
      tags: ["payments", "revenue"],
      language: "TypeScript",
      on_call: "payments-oncall",
      status: "Done",
      issue_type: "Bug",
      enabled: false,
      slo_defined: false,
    },
  },
  {
    identifier: "analytics",
    title: "Analytics Pipeline",
    properties: {
      tier: "Tier 3",
      owner: "Data",
      tags: [],
      language: "Scala",
      on_call: "data-oncall",
      status: "Blocked",
      issue_type: "Task",
      enabled: true,
      slo_defined: false,
    },
  },
  {
    identifier: "cdn",
    title: "CDN Edge",
    properties: {
      tier: "Tier 2",
      owner: "Infra",
      tags: ["infra", "edge"],
      language: "Rust",
      on_call: "infra-oncall",
      status: "Done",
      issue_type: "Task",
      enabled: true,
      slo_defined: true,
    },
  },
  {
    identifier: "mobile-api",
    title: "Mobile API",
    properties: {
      tier: "Tier 2",
      owner: "Mobile",
      tags: ["mobile", "api"],
      language: "Kotlin",
      on_call: "mobile-oncall",
      status: "In Progress",
      issue_type: "Story",
      enabled: true,
      slo_defined: true,
    },
  },
  {
    identifier: "legacy-crm",
    title: "Legacy CRM",
    properties: {
      tier: "Tier 3",
      owner: "Sales Ops",
      tags: ["legacy"],
      language: "PHP",
      on_call: "",
      status: "To Do",
      issue_type: "Bug",
      enabled: false,
      slo_defined: false,
    },
  },
  {
    identifier: "feature-flags",
    title: "Feature Flags",
    properties: {
      tier: "Tier 2",
      owner: "Platform",
      tags: ["platform", "config"],
      language: "Go",
      on_call: "platform-oncall",
      status: "Done",
      issue_type: "Task",
      enabled: true,
      slo_defined: true,
    },
  },
];
